---
title: "Tuberculosis Bulk RNA-seq Analysis"
format:
  pdf:
    toc: true
    number-sections: true
    geometry: "margin=0.5in"
    fontsize: 11pt
execute:
  warning: false
knitr:
  opts_chunk:
    fig.align: "center"
---

# Downloading and Formatting the Data
(download data from GSE, establish needed local directories, format data objects)

(describe following code)
```{r}
#| label: Setup

library(tidyverse) # dplyr, tidyr, tibble, readr
library(readxl)
library(Biobase)
library(GEOquery)

dir.create(file.path("data_raw"), showWarnings = FALSE) # establish directory to raw data downloads

supplemental_dir <- file.path("data_raw", "GSE107994") # establish path to specific study directory
```

(describe following code)
```{r}
#| label: Download-counts

if (!dir.exists(supplemental_dir) || length(list.files(supplemental_dir)) == 0) { # checks for supplemental files from GSE107994
  getGEOSuppFiles("GSE107994", baseDir = "data_raw") # accesses GEO for supplemental files (gene counts for all samples)
}

counts_file <- list.files( # grabs the specific file name for the raw gene counts data
  path = supplemental_dir,
  pattern = "Raw_counts.*Leicester.*\\.xlsx$",
  full.names = TRUE
)

counts <- readxl::read_xlsx(counts_file) # function to import .xlsx file as data table
```

(describe following code)
```{r}
#| label: Download-phenotypes

gse <- getGEO("GSE107994", GSEMatrix = TRUE) # grabs the series matrix from GEO
phenotypes <- Biobase::pData(gse[[1]]) |> as_tibble() # formats GSE download as tabular sample metadata
```

(describe following code)
```{r}
#| label: Store-data

dir.create("data_processed", showWarnings = FALSE) # create data_processed directory folder if it does not exist

readr::write_tsv(phenotypes, file.path("data_processed", "GSE107994_phenotypes.tsv")) # save phenotypes locally
readr::write_tsv(counts, file.path("data_processed", "GSE107994_counts_raw.tsv")) # save counts locally
```

{{< pagebreak >}}

# Inspecting the Data
(snapshot of counts and phenotypes tables, )
```{r}
#| label: Inspect-data

print(counts)

print(phenotypes)
```

{{< pagebreak >}}

# Data Cleanup
(standardize raw gene counts, reformat to cases x genes)
